GET http://127.0.0.1:3000/auth/ HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzIxMjM1NzcxfQ.EwMd7QQZUOEAteHzw27nGxAzNtALuPJOinV1zpWiDz7XLIit40kAEA4sPrEpKD5PhwEHv-lfh2dhKGRBplefNtCyuinrAd3d-loaF21GVD4ba-5ykXgqad0u3sTZIcJDBn19m01fa6nS2ClkEXOTd5seyxbAfuUeC5PBQEaVdl8rVg5edZLXizoix2tuGy1CTmrNRIF7X-5rEiNmga0l14Zf46ulVe7O9ssnNYh9ElWX7P30tYRFH_dJgxtEHBMcM5qu3levI1Gouh0VY5bO2SHIV_Q5XtXPRkksFNOJbeDDNmkfzrY2WGT8UvzSMcZkkAxHeEpkf45v8BauxkNfqeQfSNex0gdPB7fAtOSjfp01UOT6LjIbwQUPGiki65V0D7UhVor19ebUlkJMPbjnQdtUPNN4TyKgr-0fOAG-4w7WC9aocQy51FsOcRt-MYcpjSs_2sp67Kirv5rv3-FatT_v054QkNRSwFsZ2zcpav55eIyJVeYuOq1L-o74Te3T2mnHQQ2ez7xPQJniR1iscoo1fzK-PxdvEc6WrsGVea9x9Q6N-OfVuSXfpAEqD0yGki785kh4wQKNh-JkuUmmiBMY-lmyXwIZKdxVSpQnv7zfAynfafzazIle-A27fi0_nmW38Y6_3QJaCngUbcpQBDxMVdZaC56RbmOFAaGBsyI

